### ISSUE TITLE
commands without output do not get database entries

### ISSUE THREAD

**Issue by jamesj2** [michabbb/laravel-scheduler-watcher#4]
I was testing with the dummy command from the readme and the database wasn't getting any database entries.  After a little digging I found the database doesn't get written to if there is no output.  After adding output to the command it worked.  I would think anytime the command is run there would be statistics regardless of output.

**Comment by michabbb** [comment]
please check my FAQ, did you read:

 >i am using [log] but there is no entry in table 'job_events'

?

my intention is to let the user decide if something gets written to the DB or not.
if your cron is **NOT** producing any output, there is nothing to log. if you want
logging anyway, you have to produce output like `$this->info('nothing to do....')`

**Comment by jamesj2** [comment]
I would like to have access to the job's start, end, duration and exit code even if there was no output.   This will allow me to very they did run correctly and for how long.

I'm converting a bunch of old cron jobs that don't output anything if they are successful.  They were built for use with crontab that would email anything that had output.  So most of them do not have any output unless there is an error.

**Comment by michabbb** [comment]
@jamesj2 you only have to change this "IF" in case you want logging without any output: https://github.com/michabbb/laravel-scheduler-watcher/blob/master/src/LaravelSchedulerWatcher.php#L72
