### ISSUE TITLE
scheduler-watcher:checklastevent not working in Laravel 8

### ISSUE THREAD

**Issue by GuidoLeibbrand** [michabbb/laravel-scheduler-watcher#6]
I have followed the instructions for the integration of nagios (see https://michabbb.gitbook.io/laravel-scheduler-watcher/nagios)

When i call:
`php artisan scheduler-watcher:checklastevent 0f517c9d32a032b84615c82461e1c864 --no-ansi`
I get the result, no matter if i use the option or not
`An option named "no-ansi" already exists.`

With help of the Maintainer, I found the reason for this problem.

In Class macropage\LaravelSchedulerWatcher\Console\SchedulerWatcherCommandCheckLastRun the signature was the problem. 

`protected $signature = 'scheduler-watcher:checklastevent {jobMD5} {--noansi}';`

If I removed "no-ansi" in the source code it worked.

Environment:
- PHP 8.0.8
- Laravel/Framework: 8.51

**Comment by michabbb** [comment]
i guess i forgot to close this issue, since this is fixed since a long time. changed param `--no-ansi` to `--noansi`
